# Generated by Django 4.2.5 on 2023-10-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DateofBirth',
        ),
    ]
