# Generated by Django 4.2.5 on 2023-10-08 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0002_remove_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DateofBirth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
