# Generated by Django 4.2.5 on 2023-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0003_user_dateofbirth_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DateofBirth',
            field=models.DateField(),
        ),
    ]
