# Generated by Django 4.2.5 on 2023-10-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0006_alter_user_dateofbirth_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Reg.user')),
                ('Courses_bought', models.IntegerField(default=0)),
                ('Quetions_asked', models.IntegerField(default=0)),
                ('Maximum_questions', models.IntegerField(default=3)),
            ],
            bases=('Reg.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Reg.user')),
                ('specialty', models.CharField(max_length=32, verbose_name='Password')),
                ('personal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='rate')),
                ('numberofSudents', models.IntegerField(default=0)),
            ],
            bases=('Reg.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_Bio',
            field=models.CharField(default=1, max_length=200, verbose_name='Bio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='DateofBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures', verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True, verbose_name='Question Name')),
                ('course_description', models.CharField(max_length=100, verbose_name='Question Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('isSolved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reg.student')),
                ('solvedby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reg.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True, verbose_name='Course Name')),
                ('course_description', models.CharField(max_length=100, verbose_name='Course Name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('numberofSudentsBought', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='media/course_pictures', verbose_name='Course Picture')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reg.teacher')),
            ],
        ),
    ]
