# Generated by Django 4.2.5 on 2023-10-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0007_student_teacher_user_personal_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isSolved',
            field=models.BooleanField(default=False, verbose_name='isSolved'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(max_length=32, verbose_name='Specialty'),
        ),
    ]
