# Generated by Django 4.2.5 on 2023-10-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0008_alter_course_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='numberofSudentsBought',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='Reg.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reg.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Courses_bought',
            field=models.IntegerField(default=0, verbose_name='Course bought'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Maximum_questions',
            field=models.IntegerField(default=3, verbose_name='Maximum_questions'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Quetions_asked',
            field=models.IntegerField(default=0, verbose_name='Quetions_asked'),
        ),
    ]
