# Generated by Django 4.2.5 on 2023-10-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0009_remove_course_numberofsudentsbought_course_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course_description',
            new_name='question_Description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='course_name',
            new_name='question_Name',
        ),
    ]
