# Generated by Django 4.2.5 on 2023-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0010_rename_course_description_question_question_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='Teacher',
            field=models.ManyToManyField(blank=True, null=True, to='Reg.teacher'),
        ),
    ]
