# Generated by Django 4.2.5 on 2023-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0011_remove_student_teacher_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='students',
            field=models.ManyToManyField(to='Reg.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_Bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bio'),
        ),
    ]
