# Generated by Django 4.2.5 on 2023-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0012_remove_course_students_student_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='Courses',
            field=models.ManyToManyField(to='Reg.course', verbose_name='Courses'),
        ),
    ]
