# Generated by Django 4.2.5 on 2023-10-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg', '0013_remove_student_students_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_Bio',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Bio'),
        ),
    ]
